    
version: 1.0.{build}
image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  project_feed: true
  disable_publish_on_pr: true

environment:
  matrix:
    - platform: Any CPU
      configuration: Release
matrix:
  fast_finish: false
  
before_build:
 - dotnet restore
 - dotnet tool install --global dotnet-sonarscanner
 - dotnet sonarscanner begin /k:"predicate-builder" /o:"celsomarques-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="287074886f2e0e848ff4e4758faee87ff827e51c"

build_script:
 - dotnet build /verbosity:quiet "Konatus.PredicateBuilder.sln"
 - dotnet pack .\Konatus.PredicateBuilder -c Release -o .\artifacts /p:NuspecFile=.\Konatus.PredicateBuilder.nuspec /p:Version=%APPVEYOR_BUILD_VERSION%
 
test_script:
 - dotnet test

after_test:
 - dotnet sonarscanner end /d:sonar.login="287074886f2e0e848ff4e4758faee87ff827e51c"
 
artifacts:
- path: .\Konatus.PredicateBuilder\artifacts\*.nupkg
  name: NuGet
  
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: l8C4clHka5NNot0A9ioX8dJ5EOo61j7KbgUM6/Divzb5jmn+osxQ/IdqvJiPpVBz
  on:
    branch: master
    appveyor_repo_tag: true
